# 异常与函数

异常和函数有着天然的联系。如果不处理函数中引发的异常，它将向上传播到调用函数的地 方。如果在那里也未得到处理，异常将继续传播，直至到达主程序(全局作用域)。如果主程序 中也没有异常处理程序，程序将终止并显示栈跟踪消息。来看一个示例:

<div class="run"></div>

```python
def faulty():
    raise Exception('Something is wrong')

def ignore_exception:
    faulty()

ignore_exception()
```

faulty 中引发的异常依次从 faulty 和 ignore_exception 向外传播，最终导致显示一条栈跟踪消息。

<div class="run"></div>

```python
def faulty():
    raise Exception('Something is wrong')

def handle_exception():
    try:
        faulty()
    except:
        print('抓住了异常')

handle_exception()
```

调用 handle_exception 时，异常最终传播到 handle_exception，并被这里的 try/except 语句处理。
